### ISSUE TITLE
"Fix of latest PR with updates" merge broke the start

### ISSUE THREAD

**Issue by jackyq2015** [Cezerin2/Server#207]
**Describe the bug**
New PR merge broke the startup. The install is fine. but the start fails. I tired the docker, it is the same error

**To Reproduce**
1. Get the updated version with last commit 2664ecb
2. npm i
3 .nmp start 
```
root@node15:/var/www/cezerin2# node --version
v8.11.3
root@node15:/var/www/cezerin2# npm start

> cezerin2@0.35.0 start /var/www/cezerin2
> node -r esm src/index.js

error: uncaughtException: Unexpected token {
/var/www/cezerin2/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
} catch {
^

SyntaxError: Unexpected token {
at Object.Module._extensions..js (module.js:663:10)
at Object.Module._extensions..js (module.js:663:10) {"error":{},"stack":"/var/www/cezerin2/node_modules/fs-extra/lib/mkdirs/make-dir.js:86\n      } catch {\n              ^\n\nSyntaxError: Unexpected token {\n    at Object.Module._extensions..js (module.js:663:10)\n    at Object.Module._extensions..js (module.js:663:10)","exception":true,"date":"Sun Apr 05 2020 18:10:05 GMT-0400 (EDT)","process":{"pid":19638,"uid":0,"gid":0,"cwd":"/var/www/cezerin2","execPath":"/root/.nvm/versions/node/v8.11.3/bin/node","version":"v8.11.3","argv":["/root/.nvm/versions/node/v8.11.3/bin/node","/var/www/cezerin2/src/index.js"],"memoryUsage":{"rss":126976000,"heapTotal":95252480,"heapUsed":58243664,"external":22108977}},"os":{"loadavg":[0.484375,0.2724609375,0.41162109375],"uptime":1457461},"trace":[{"column":10,"file":"module.js","function":"Module._extensions..js","line":663,"method":".js","native":false},{"column":10,"file":"module.js","function":"Module._extensions..js","line":663,"method":".js","native":false}]}
(node:19638) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine,pass option { useUnifiedTopology: true } to the MongoClient constructor.
info: MongoDB connected successfully
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cezerin2@0.35.0 start: `node -r esm src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cezerin2@0.35.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-05T22_10_08_939Z-debug.log
**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
```

**Comment by vamcart** [comment]
> **Describe the bug**
> New PR merge broke the startup. The install is fine. but the start fails. I tired the docker, it is the same error
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> ```

Hi!

Can you check this PR - https://github.com/Cezerin2/cezerin2/pull/206
!?

Is it working for you?!

**Comment by vamcart** [comment]
We have updated all apps:

https://github.com/cezerin2/cezerin2
https://github.com/cezerin2/cezerin2-store
https://github.com/cezerin2/cezerin2-admin

Please, test it, how it's working now.

**Comment by vamcart** [comment]
> **Describe the bug**
> New PR merge broke the startup. The install is fine. but the start fails. I tired the docker, it is the same error
> Add any other context about the problem here.
> ```

We have updated all apps:

https://github.com/cezerin2/cezerin2
https://github.com/cezerin2/cezerin2-store
https://github.com/cezerin2/cezerin2-admin

Please, test it, how it's working now.

**Comment by jackyq2015** [comment]
works fine now. Thanks!
