### ISSUE TITLE
Could not add new product in admin

### ISSUE THREAD

**Issue by jsam6** [Cezerin2/Server#267]
**Describe the bug**
Could not add new products from cezerin-admin.

Error:
`
error: ReferenceError: length is not defined
at ProductsService.getValidDocumentForInsert (/Users/sam/workspace/cezerin2/build/services/products/products.js:544:21)
    at ProductsService.addProduct (/Users/sam/workspace/cezerin2/build/services/products/products.js:494:21)
    at ProductsRoute.addProduct (/Users/sam/workspace/cezerin2/build/routes/products.js:61:28)
    at Layer.handle [as handle_request] (/Users/sam/workspace/cezerin2/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/sam/workspace/cezerin2/node_modules/express/lib/router/route.js:137:13)
    at ProductsRoute.checkUserScope (/Users/sam/workspace/cezerin2/build/lib/security.js:48:9)
    at Layer.handle [as handle_request] (/Users/sam/workspace/cezerin2/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/sam/workspace/cezerin2/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/sam/workspace/cezerin2/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/sam/workspace/cezerin2/node_modules/express/lib/router/layer.js:95:5)
`
**To Reproduce**
I set up cezerin2, cezerin2-store, cezerin2-admin based on this guide lines, [cezerin](https://github.com/Cezerin2/cezerin2/blob/master/docs/using-source-code.md)

**Expected behavior**
I've tried adding new products in admin.cezerin.net, and everything seems to be working fine.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Catalina OS
- Browser: Chrome

**Comment by jsam6** [comment]
Issue resolve.

Apparently
at `src/services/products/product.ts` file

at `getValidDocumentForInsert` function, 
`slug: { length },` was expecting a `length` which has yet to be defined.

Keep up the great work updating this project!
